# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.7.0
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build:
    machine:
      image: ubunutu-2004:202104-01
      docker_layer_caching: true
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Get ECR Credentials
          command:  aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}

      - docker/build:
          image: ${AWS_ECS_ACCOUNT_URL}/multi-dbt
          tag: $CIRCLE_SHA1
      - docker/push:
          image: ${AWS_ECS_ACCOUNT_URL}/multi-dbt
          tag: $CIRCLE_SHA1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only: master
