# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - aws-cli/install
      - run:
          name: Get ECR Credentials
          command:  aws ecr get-login-password --region us-east-1 |
            docker login --username AWS --password-stdin ${AWS_ECS_ACCOUNT_URL}
      - run:
          name: Build image
          command: |
            docker build -t ${AWS_ECR_ACCOUNT_URL}/multi-dbt:$CIRCLE_SHA1 .
      - run:
          name: Push image
          command: docker push ${AWS_ECR_ACCOUNT_URL}/multi-dbt:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only: master
